### ISSUE TITLE
Pkg development chores

### ISSUE THREAD

**Issue by vedhav** [donyunardi/multiloadr#46]
Will be nice to set up `lintr` and `styler`. Perhaps a pkgdown site after that ;)

**Comment by donyunardi** [comment]
Yup, let's do it:

- [x] add .lintr
- [x] add pre-commit with styler hook

**Comment by donyunardi** [comment]
I'll move pkgdown to another issue because of the scope.

**Comment by vedhav** [comment]
Probably for the best, considering that a refactor might happen and we can benefit from not rewriting the usage vignette.
